let failwith_error_code (i: int) : 'a = Stdlib.failwith (string_of_int i)